// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9H5ug7aiTzbylLmV-Ei4C0R1x-BW7izo',
    appId: '1:47060593395:web:a28486097b0349394ae586',
    messagingSenderId: '47060593395',
    projectId: 'gossip-letest',
    authDomain: 'gossip-letest.firebaseapp.com',
    storageBucket: 'gossip-letest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCft2COb1GCypm3gI0Ogimd5DujiciQtbs',
    appId: '1:47060593395:android:52a33327b547482e4ae586',
    messagingSenderId: '47060593395',
    projectId: 'gossip-letest',
    storageBucket: 'gossip-letest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyenFYzIuWeQUMKBHUcJG3wdy-27W4DM',
    appId: '1:47060593395:ios:01393d837b3b4cb34ae586',
    messagingSenderId: '47060593395',
    projectId: 'gossip-letest',
    storageBucket: 'gossip-letest.appspot.com',
    iosBundleId: 'com.example.gossipLetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyenFYzIuWeQUMKBHUcJG3wdy-27W4DM',
    appId: '1:47060593395:ios:7b7589882a6d72634ae586',
    messagingSenderId: '47060593395',
    projectId: 'gossip-letest',
    storageBucket: 'gossip-letest.appspot.com',
    iosBundleId: 'com.example.gossipLetest.RunnerTests',
  );
}
